// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyFirstWebApiProj.Data;

#nullable disable

namespace MyFirstWebApiProj.Migrations
{
    [DbContext(typeof(FirstApiContext))]
    partial class FirstApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyFirstWebApiProj.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearPublished")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "George Orwell",
                            Title = "1984",
                            YearPublished = 2004
                        },
                        new
                        {
                            Id = 2,
                            Author = "Yuval Noah Harari",
                            Title = "Sapiens",
                            YearPublished = 2011
                        },
                        new
                        {
                            Id = 3,
                            Author = "Muhammad Iqbal",
                            Title = "Recdonstruction of Religious Thoughts in Islam",
                            YearPublished = 1930
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
